Add node order
smartcontractkit/operator-ui pull request #44
Opened 2023-06-12 08:18 UTC by george-dorin

Add node order column in the `Nodes` screen

2023-06-13 15:14 UTC, pinebit reviewed
LGTM, and I will delegate approval to @vyzaldysanchez because of his better GQL knowledge.

2023-06-14 16:17 UTC, vyzaldysanchez requested changes
Would you be so kind to post image(s) of how this look, so we can document in the PR that the changes are working as expected?

2023-06-14 16:38 UTC, george-dorin commented
@vyzaldysanchez Sure updated the PR comment with the a image of the new Nodes screen

2023-06-14 16:49 UTC, vyzaldysanchez approved these changes

2023-06-14 16:58 UTC, jmank88 approved these changes

2023-06-14 17:00 UTC, merged